### ISSUE TITLE
GPL License Compliance Issue?

### ISSUE THREAD

**Issue by laurijamsa** [joltwallet/jolt_wallet#28]
A cool project, well done.

However, I have to say that I'm not happy to see a GPL copyleft license there. The license makes it impossible or hard to reuse parts of the code on anything else.

And, I'm afraid, there is more. Because ESP32's WiFi and Bluetooth stacks are not open, GPL cannot legally be used on the firmware application provided to users. That's because GPL applies to the project as the whole and any of your (or someone else's) customers, by the right given by GPL, may request source codes of the full project, which obviously cannot be provided due to the closed binaries used.
 
Do you have plans to change the license to something else?

**Comment by jamescoxon** [comment]
Thanks for your feedback, we are currently in the process of getting advice and will get back to you soon with that. Obviously want to find the most sensible balance so that all can benefit.
