### ISSUE TITLE
sys/select.h: No such file or directory

### ISSUE THREAD

**Issue by abroba** [joltwallet/jolt_wallet#34]
Folks,
I'm trying to install your code on a MacBook Pro running macOS 10.13.5, Xcode 9.4.1, following your instructions 

At the final step: MacOS/ESP32/10. Verify the setup..., I get the following error:

/Users/pedropaulocf/JOLT/esp-idf/components/lwip/include/lwip/port/lwipopts.h:42:24: fatal error: sys/select.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/websockets.dir/lib/core/alloc.c.o] Error 1
make[3]: *** [CMakeFiles/websockets.dir/all] Error 2
make[2]: *** [all] Error 2
make[1]: *** [build] Error 2
make: *** [component-libwebsockets-build] Error 2

it looks like a relatively recent Espressif IDF change is the source of the error. On my old copy of esp-idf the folder  idf/components/newlib/platform_include/sys/ doesn't exist.

**Comment by jamescoxon** [comment]
Hi

So we've been having issues with the new versions of ESP-IDF (it seems they have a habit of breaking things suddenly). I've come across this bug before (I can tell as when i did some research I had visited some of the sites before). I recommend using an older version of ESP-IDF - if you check out this section of the Linux guide you'll find how to roll back the ESP-IDF:
https://github.com/joltwallet/jolt_wallet/blob/master/docs/build-linux.md#install-espressif-iot-development-framework

`git clone --recursive https://github.com/espressif/esp-idf.git

cd esp-idf

git checkout 8c307

git submodule update --init --recursive`

It is probably a good idea to start again with the installation of esp-idf.

**Comment by abroba** [comment]
Followed all the steps
New error

esptool.py v2.3.1
Building partitions from /Users/pedropaulocf/JOLT/esp-idf/components/partition_table/partitions_singleapp.csv...
Traceback (most recent call last):
  File "/Users/pedropaulocf/JOLT/esp-idf/components/partition_table/gen_esp32part.py", line 423, in <module>
    main()
  File "/Users/pedropaulocf/JOLT/esp-idf/components/partition_table/gen_esp32part.py", line 395, in main
    table_size = table.flash_size()
  File "/Users/pedropaulocf/JOLT/esp-idf/components/partition_table/gen_esp32part.py", line 122, in flash_size
    last = sorted(self, reverse=True)[0]
TypeError: '<' not supported between instances of 'PartitionDefinition' and 'PartitionDefinition'
make: *** [/Users/pedropaulocf/JOLT/build/partitions_singleapp.bin] Error 1

**Comment by jamescoxon** [comment]
Hey

Looks like this is to do with the version of python you are using - check out https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/issues/147 for more information.
