### ISSUE TITLE
E (482) esp_image: Image length 1068192 doesn't fit in partition length 1048576

### ISSUE THREAD

**Issue by NaelsonDouglas** [joltwallet/jolt_wallet#35]
I had this error, whose I already fixed.

I'm posting it here just to keep things registered.

`

> I (481) esp_image: segment 6: paddr=0x00114c78 vaddr=0x400c0000 size=0x00000 (     0) load
> 
> E (482) esp_image: Image length 1068192 doesn't fit in partition length 1048576
> 
> E (487) boot: Factory app partition is not bootable
> 
> E (493) boot: No bootable app partitions in the partition table
> 
> user code done
> 

`

**Comment by NaelsonDouglas** [comment]
Here was my solution:
1: edit the file: 

> <ESPIDF>/components/partition_table/partitions_singleapp.csv

2: Change the value on "factory, app"  1M to 0x180000

More details [here](https://github.com/micropython/micropython-esp32/issues/235)

**Comment by TranPhucVinh** [comment]
Thanks for sharing the information, your solution works perfectly.
